using Forma.Editor;
using UnityEditor;
using UnityEngine;

// Compatibility entry point for the current FORMA Unity 6 pipeline.
// The project ships GLB source avatars in Assets/FORMA/Sources. Their Resources
// prefabs and AnimatorControllers are generated by FormaGlbAnimBaker; the former
// FBX/Rigged setup path is deliberately not used by this project.
public static class MAC_Forma_Setup
{
    [MenuItem("Tools/FORMA/Setup Reference Avatars")]
    public static void SetupFromMenu()
    {
        FormaGlbAnimBaker.BakeAll();
        Debug.Log(Build());
    }

    public static string Build()
    {
        FormaGlbAnimBaker.BakeAll();
        return "[FORMA] GLB avatar bake completed. Open Assets/FORMA/Scenes/FORMA_Studio.unity and press Play.";
    }
}
